import { useLoaderData } from "react-router";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";
import { requireAdmin } from "~/utils/admin";
import type { Route } from "./+types/index";

export async function loader(args: Route.LoaderArgs) {
  await requireAdmin(args);

  // Mock data for now - replace with real database queries
  const adminData = {
    totalCustomers: 156,
    activeCustomers: 142,
    totalLeadsGenerated: 2847,
    totalRevenue: 47890,
    avgROAS: 4.2,
    customerRetention: 89,
    recentCustomers: [
      {
        id: 1,
        name: "Joe's Plumbing",
        email: "joe@joesplumbing.com",
        status: "Active",
        subscription: "$99/month",
        leadsThisMonth: 47,
        revenue: 8400,
        joinDate: "2024-01-15",
      },
      {
        id: 2,
        name: "Fast Electric",
        email: "mike@fastelectric.com",
        status: "Active",
        subscription: "$149/month",
        leadsThisMonth: 23,
        revenue: 3200,
        joinDate: "2024-02-01",
      },
      {
        id: 3,
        name: "24/7 HVAC Services",
        email: "sarah@247hvac.com",
        status: "Active",
        subscription: "$199/month",
        leadsThisMonth: 31,
        revenue: 5600,
        joinDate: "2024-01-28",
      },
      {
        id: 4,
        name: "City Roofing",
        email: "john@cityroofing.com",
        status: "Cancelled",
        subscription: "Cancelled",
        leadsThisMonth: 0,
        revenue: 0,
        joinDate: "2024-01-10",
      },
    ],
  };

  return adminData;
}

export default function AdminDashboard() {
  const data = useLoaderData<typeof loader>();

  return (
    <div className="flex flex-1 flex-col">
      <div className="@container/main flex flex-1 flex-col gap-2">
        <div className="flex flex-col gap-4 py-4 md:gap-6 md:py-6">
          {/* Admin Header */}
          <div className="px-4 lg:px-6">
            <div className="flex items-center gap-2 mb-6">
              <h1 className="text-2xl font-bold">🔐 Admin Dashboard</h1>
              <Badge variant="destructive">Admin Only</Badge>
            </div>
          </div>

          {/* Overview Stats */}
          <div className="px-4 lg:px-6">
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Total Customers</CardTitle>
                  <span className="text-2xl">👥</span>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{data.totalCustomers}</div>
                  <p className="text-xs text-muted-foreground">
                    {data.activeCustomers} active subscriptions
                  </p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Leads Generated</CardTitle>
                  <span className="text-2xl">📞</span>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{data.totalLeadsGenerated.toLocaleString()}</div>
                  <p className="text-xs text-muted-foreground">This month across all customers</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Customer Revenue</CardTitle>
                  <span className="text-2xl">💰</span>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">${data.totalRevenue.toLocaleString()}</div>
                  <p className="text-xs text-muted-foreground">Generated by customers this month</p>
                </CardContent>
              </Card>

              <Card>
                <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                  <CardTitle className="text-sm font-medium">Retention Rate</CardTitle>
                  <span className="text-2xl">📈</span>
                </CardHeader>
                <CardContent>
                  <div className="text-2xl font-bold">{data.customerRetention}%</div>
                  <p className="text-xs text-muted-foreground">
                    Avg ROAS: {data.avgROAS}x
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>

          {/* Recent Customers */}
          <div className="px-4 lg:px-6">
            <Card>
              <CardHeader>
                <CardTitle>Recent Customers</CardTitle>
                <CardDescription>
                  Latest customer activity and performance
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b text-left">
                        <th className="pb-3 font-medium text-sm">Customer</th>
                        <th className="pb-3 font-medium text-sm">Status</th>
                        <th className="pb-3 font-medium text-sm">Subscription</th>
                        <th className="pb-3 font-medium text-sm">Leads/Month</th>
                        <th className="pb-3 font-medium text-sm">Revenue</th>
                        <th className="pb-3 font-medium text-sm">Join Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {data.recentCustomers.map((customer) => (
                        <tr key={customer.id} className="border-b">
                          <td className="py-3">
                            <div>
                              <div className="font-medium">{customer.name}</div>
                              <div className="text-sm text-muted-foreground">{customer.email}</div>
                            </div>
                          </td>
                          <td className="py-3">
                            <Badge
                              variant={customer.status === "Active" ? "default" : "secondary"}
                            >
                              {customer.status}
                            </Badge>
                          </td>
                          <td className="py-3 text-sm">{customer.subscription}</td>
                          <td className="py-3 text-sm font-medium">{customer.leadsThisMonth}</td>
                          <td className="py-3 text-sm">${customer.revenue.toLocaleString()}</td>
                          <td className="py-3 text-sm text-muted-foreground">
                            {new Date(customer.joinDate).toLocaleDateString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}